version: '3.8'

services:
  app:
    build: .
    platform: linux/amd64
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5433/overview-ai
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: overview-ai
    ports:
      - "5433:5432"


volumes:
  postgres_data:
