"""add timestamps to detections

Revision ID: 84490f6478a9
Revises: aa2c52eb7310
Create Date: 2024-04-12 15:12:38.788011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84490f6478a9'
down_revision = 'aa2c52eb7310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
